<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:mc="urn:oio:medcom:chronicdataset:1.0.0"
	xmlns:tns="urn:oio:medcom:chronicdataset:all:1.0.0" 
	name="ChronicDatasetService"
	targetNamespace="urn:oio:medcom:chronicdataset:all:1.0.0">
	<wsdl:types>
		<xs:schema targetNamespace="urn:oio:medcom:chronicdataset:all:1.0.0" elementFormDefault="qualified">
			<xs:include schemaLocation="ChronicDatasetService.xsd"/>
			<xs:import namespace="urn:oio:medcom:chronicdataset:1.0.0" schemaLocation="Fault.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="FaultMessage">
		<wsdl:part name="fault" element="mc:Fault"/>
	</wsdl:message>
	<wsdl:message name="GetChronicDatasetRequestMessage">
		<wsdl:part name="parameter" element="tns:GetChronicDatasetRequestMessage"/>
	</wsdl:message>
	<wsdl:message name="GetChronicDatasetResponseMessage">
		<wsdl:part name="parameter" element="tns:GetChronicDatasetResponseMessage"/>
	</wsdl:message>
	<wsdl:portType name="ChronicDatasetPortType">
		<wsdl:operation name="GetChronicDataset">
			<wsdl:input message="tns:GetChronicDatasetRequestMessage"/>
			<wsdl:output message="tns:GetChronicDatasetResponseMessage"/>
			<wsdl:fault name="Fault" message="tns:FaultMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ChronicDatasetBinding" type="tns:ChronicDatasetPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetChronicDataset">
			<soap:operation soapAction="GetChronicDataset"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="Fault">
				<soap:fault name="Fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ChronicDatasetService">
		<wsdl:port name="ChronicDatasetPort" binding="tns:ChronicDatasetBinding">
			<soap:address location="http://localhost/NoServiceHere"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
